version: '3.8'

services:
  mi-gpt-go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mi-gpt-go
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # 服务器基本配置
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      
      # 数据库文件路径
      - DB_PATH=/app/data/app.db
      
    volumes:
      # 持久化数据库文件
      - ./data:/app/data
      # 持久化日志文件（可选）
      - ./logs:/app/logs
      
    # 健康检查
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      
    networks:
      - mi-gpt-network

# 网络配置
networks:
  mi-gpt-network:
    driver: bridge

# 卷配置
volumes:
  mi-gpt-data:
    driver: local 